version: '3.6'
services:

  vault:
    image: hashicorp/vault:1.15
    container_name: vault-server
    ports:
      - "8200:8200" # Puerto por defecto de Vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token" # Token de acceso de desarrollo para pruebas
    command: server -dev -dev-root-token-id=root-token

  mysql:
    container_name: mysql_db_container_name
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_name
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - volume_mysql_db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

volumes:
  volume_mysql_db:
    external: false